Respects the proportion of columns chosen in Select Layout
eea/volto-columns-block pull request #63
Opened 2023-01-24 21:40 UTC by wesleybl

ColumnsBlockEdit's `componentDidUpdate` method was always setting proportions to the default variation proportions, regardless of the user's choice. That code has been removed, and now the user's choice is respected.

Fixes #57

2023-01-24 21:43 UTC, wesleybl commented
@avoinea @tiberiuichim can you please have a look here?

2023-01-31 19:24 UTC, wesleybl commented
@avoinea @tiberiuichim I did rebase here. Can you please have a look here?

2023-02-07 15:23 UTC, wesleybl commented
@tiberiuichim can you please have a look here?

2023-02-08 12:52 UTC, tiberiuichim commented
@wesleybl Thanks for fixing this!

2023-02-08 12:54 UTC, tiberiuichim requested changes
@wesleybl There is one problem with this fix. To reproduce:

- create a 2 columns layout
- add a new column

The new column is wrapped, instead of sitting on the same row.

2023-02-08 14:59 UTC, wesleybl commented
@tiberiuichim thanks for testing! I really see this problem. I'll have a look later.

2023-02-09 22:31 UTC, wesleybl commented
@tiberiuichim I fixed it now. The definition of `initialLayoutSelection` was wrong. If length of previus columns is 0, so we are in the initial selection. Can you please have a look?

CC @avoinea

2023-02-10 08:44 UTC, tiberiuichim approved these changes

2023-02-10 08:44 UTC, merged